package com.wcq.tang.model;

import java.util.Date;

public class Corpus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corpus.corpus_id
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private Long corpusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corpus.original_id
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private Long originalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corpus.uploader
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private Long uploader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corpus.corpus_date
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private Date corpusDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corpus.standard_content
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private String standardContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corpus.cixin_content
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private String cixinContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corpus.original_content
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private String originalContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column corpus.participled
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private Boolean participled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corpus.corpus_id
     *
     * @return the value of corpus.corpus_id
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Long getCorpusId() {
        return corpusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corpus.corpus_id
     *
     * @param corpusId the value for corpus.corpus_id
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setCorpusId(Long corpusId) {
        this.corpusId = corpusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corpus.original_id
     *
     * @return the value of corpus.original_id
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Long getOriginalId() {
        return originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corpus.original_id
     *
     * @param originalId the value for corpus.original_id
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setOriginalId(Long originalId) {
        this.originalId = originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corpus.uploader
     *
     * @return the value of corpus.uploader
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Long getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corpus.uploader
     *
     * @param uploader the value for corpus.uploader
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setUploader(Long uploader) {
        this.uploader = uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corpus.corpus_date
     *
     * @return the value of corpus.corpus_date
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Date getCorpusDate() {
        return corpusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corpus.corpus_date
     *
     * @param corpusDate the value for corpus.corpus_date
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setCorpusDate(Date corpusDate) {
        this.corpusDate = corpusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corpus.standard_content
     *
     * @return the value of corpus.standard_content
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public String getStandardContent() {
        return standardContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corpus.standard_content
     *
     * @param standardContent the value for corpus.standard_content
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setStandardContent(String standardContent) {
        this.standardContent = standardContent == null ? null : standardContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corpus.cixin_content
     *
     * @return the value of corpus.cixin_content
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public String getCixinContent() {
        return cixinContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corpus.cixin_content
     *
     * @param cixinContent the value for corpus.cixin_content
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setCixinContent(String cixinContent) {
        this.cixinContent = cixinContent == null ? null : cixinContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corpus.original_content
     *
     * @return the value of corpus.original_content
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public String getOriginalContent() {
        return originalContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corpus.original_content
     *
     * @param originalContent the value for corpus.original_content
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setOriginalContent(String originalContent) {
        this.originalContent = originalContent == null ? null : originalContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column corpus.participled
     *
     * @return the value of corpus.participled
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Boolean getParticipled() {
        return participled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column corpus.participled
     *
     * @param participled the value for corpus.participled
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setParticipled(Boolean participled) {
        this.participled = participled;
    }
}