package com.wcq.tang.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CorpusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public CorpusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCorpusIdIsNull() {
            addCriterion("corpus_id is null");
            return (Criteria) this;
        }

        public Criteria andCorpusIdIsNotNull() {
            addCriterion("corpus_id is not null");
            return (Criteria) this;
        }

        public Criteria andCorpusIdEqualTo(Long value) {
            addCriterion("corpus_id =", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdNotEqualTo(Long value) {
            addCriterion("corpus_id <>", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdGreaterThan(Long value) {
            addCriterion("corpus_id >", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdGreaterThanOrEqualTo(Long value) {
            addCriterion("corpus_id >=", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdLessThan(Long value) {
            addCriterion("corpus_id <", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdLessThanOrEqualTo(Long value) {
            addCriterion("corpus_id <=", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdIn(List<Long> values) {
            addCriterion("corpus_id in", values, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdNotIn(List<Long> values) {
            addCriterion("corpus_id not in", values, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdBetween(Long value1, Long value2) {
            addCriterion("corpus_id between", value1, value2, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdNotBetween(Long value1, Long value2) {
            addCriterion("corpus_id not between", value1, value2, "corpusId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdIsNull() {
            addCriterion("original_id is null");
            return (Criteria) this;
        }

        public Criteria andOriginalIdIsNotNull() {
            addCriterion("original_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalIdEqualTo(Long value) {
            addCriterion("original_id =", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdNotEqualTo(Long value) {
            addCriterion("original_id <>", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdGreaterThan(Long value) {
            addCriterion("original_id >", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdGreaterThanOrEqualTo(Long value) {
            addCriterion("original_id >=", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdLessThan(Long value) {
            addCriterion("original_id <", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdLessThanOrEqualTo(Long value) {
            addCriterion("original_id <=", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdIn(List<Long> values) {
            addCriterion("original_id in", values, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdNotIn(List<Long> values) {
            addCriterion("original_id not in", values, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdBetween(Long value1, Long value2) {
            addCriterion("original_id between", value1, value2, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdNotBetween(Long value1, Long value2) {
            addCriterion("original_id not between", value1, value2, "originalId");
            return (Criteria) this;
        }

        public Criteria andUploaderIsNull() {
            addCriterion("uploader is null");
            return (Criteria) this;
        }

        public Criteria andUploaderIsNotNull() {
            addCriterion("uploader is not null");
            return (Criteria) this;
        }

        public Criteria andUploaderEqualTo(Long value) {
            addCriterion("uploader =", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotEqualTo(Long value) {
            addCriterion("uploader <>", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderGreaterThan(Long value) {
            addCriterion("uploader >", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderGreaterThanOrEqualTo(Long value) {
            addCriterion("uploader >=", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderLessThan(Long value) {
            addCriterion("uploader <", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderLessThanOrEqualTo(Long value) {
            addCriterion("uploader <=", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderIn(List<Long> values) {
            addCriterion("uploader in", values, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotIn(List<Long> values) {
            addCriterion("uploader not in", values, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderBetween(Long value1, Long value2) {
            addCriterion("uploader between", value1, value2, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotBetween(Long value1, Long value2) {
            addCriterion("uploader not between", value1, value2, "uploader");
            return (Criteria) this;
        }

        public Criteria andCorpusDateIsNull() {
            addCriterion("corpus_date is null");
            return (Criteria) this;
        }

        public Criteria andCorpusDateIsNotNull() {
            addCriterion("corpus_date is not null");
            return (Criteria) this;
        }

        public Criteria andCorpusDateEqualTo(Date value) {
            addCriterion("corpus_date =", value, "corpusDate");
            return (Criteria) this;
        }

        public Criteria andCorpusDateNotEqualTo(Date value) {
            addCriterion("corpus_date <>", value, "corpusDate");
            return (Criteria) this;
        }

        public Criteria andCorpusDateGreaterThan(Date value) {
            addCriterion("corpus_date >", value, "corpusDate");
            return (Criteria) this;
        }

        public Criteria andCorpusDateGreaterThanOrEqualTo(Date value) {
            addCriterion("corpus_date >=", value, "corpusDate");
            return (Criteria) this;
        }

        public Criteria andCorpusDateLessThan(Date value) {
            addCriterion("corpus_date <", value, "corpusDate");
            return (Criteria) this;
        }

        public Criteria andCorpusDateLessThanOrEqualTo(Date value) {
            addCriterion("corpus_date <=", value, "corpusDate");
            return (Criteria) this;
        }

        public Criteria andCorpusDateIn(List<Date> values) {
            addCriterion("corpus_date in", values, "corpusDate");
            return (Criteria) this;
        }

        public Criteria andCorpusDateNotIn(List<Date> values) {
            addCriterion("corpus_date not in", values, "corpusDate");
            return (Criteria) this;
        }

        public Criteria andCorpusDateBetween(Date value1, Date value2) {
            addCriterion("corpus_date between", value1, value2, "corpusDate");
            return (Criteria) this;
        }

        public Criteria andCorpusDateNotBetween(Date value1, Date value2) {
            addCriterion("corpus_date not between", value1, value2, "corpusDate");
            return (Criteria) this;
        }

        public Criteria andStandardContentIsNull() {
            addCriterion("standard_content is null");
            return (Criteria) this;
        }

        public Criteria andStandardContentIsNotNull() {
            addCriterion("standard_content is not null");
            return (Criteria) this;
        }

        public Criteria andStandardContentEqualTo(String value) {
            addCriterion("standard_content =", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentNotEqualTo(String value) {
            addCriterion("standard_content <>", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentGreaterThan(String value) {
            addCriterion("standard_content >", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentGreaterThanOrEqualTo(String value) {
            addCriterion("standard_content >=", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentLessThan(String value) {
            addCriterion("standard_content <", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentLessThanOrEqualTo(String value) {
            addCriterion("standard_content <=", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentLike(String value) {
            addCriterion("standard_content like", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentNotLike(String value) {
            addCriterion("standard_content not like", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentIn(List<String> values) {
            addCriterion("standard_content in", values, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentNotIn(List<String> values) {
            addCriterion("standard_content not in", values, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentBetween(String value1, String value2) {
            addCriterion("standard_content between", value1, value2, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentNotBetween(String value1, String value2) {
            addCriterion("standard_content not between", value1, value2, "standardContent");
            return (Criteria) this;
        }

        public Criteria andCixinContentIsNull() {
            addCriterion("cixin_content is null");
            return (Criteria) this;
        }

        public Criteria andCixinContentIsNotNull() {
            addCriterion("cixin_content is not null");
            return (Criteria) this;
        }

        public Criteria andCixinContentEqualTo(String value) {
            addCriterion("cixin_content =", value, "cixinContent");
            return (Criteria) this;
        }

        public Criteria andCixinContentNotEqualTo(String value) {
            addCriterion("cixin_content <>", value, "cixinContent");
            return (Criteria) this;
        }

        public Criteria andCixinContentGreaterThan(String value) {
            addCriterion("cixin_content >", value, "cixinContent");
            return (Criteria) this;
        }

        public Criteria andCixinContentGreaterThanOrEqualTo(String value) {
            addCriterion("cixin_content >=", value, "cixinContent");
            return (Criteria) this;
        }

        public Criteria andCixinContentLessThan(String value) {
            addCriterion("cixin_content <", value, "cixinContent");
            return (Criteria) this;
        }

        public Criteria andCixinContentLessThanOrEqualTo(String value) {
            addCriterion("cixin_content <=", value, "cixinContent");
            return (Criteria) this;
        }

        public Criteria andCixinContentLike(String value) {
            addCriterion("cixin_content like", value, "cixinContent");
            return (Criteria) this;
        }

        public Criteria andCixinContentNotLike(String value) {
            addCriterion("cixin_content not like", value, "cixinContent");
            return (Criteria) this;
        }

        public Criteria andCixinContentIn(List<String> values) {
            addCriterion("cixin_content in", values, "cixinContent");
            return (Criteria) this;
        }

        public Criteria andCixinContentNotIn(List<String> values) {
            addCriterion("cixin_content not in", values, "cixinContent");
            return (Criteria) this;
        }

        public Criteria andCixinContentBetween(String value1, String value2) {
            addCriterion("cixin_content between", value1, value2, "cixinContent");
            return (Criteria) this;
        }

        public Criteria andCixinContentNotBetween(String value1, String value2) {
            addCriterion("cixin_content not between", value1, value2, "cixinContent");
            return (Criteria) this;
        }

        public Criteria andOriginalContentIsNull() {
            addCriterion("original_content is null");
            return (Criteria) this;
        }

        public Criteria andOriginalContentIsNotNull() {
            addCriterion("original_content is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalContentEqualTo(String value) {
            addCriterion("original_content =", value, "originalContent");
            return (Criteria) this;
        }

        public Criteria andOriginalContentNotEqualTo(String value) {
            addCriterion("original_content <>", value, "originalContent");
            return (Criteria) this;
        }

        public Criteria andOriginalContentGreaterThan(String value) {
            addCriterion("original_content >", value, "originalContent");
            return (Criteria) this;
        }

        public Criteria andOriginalContentGreaterThanOrEqualTo(String value) {
            addCriterion("original_content >=", value, "originalContent");
            return (Criteria) this;
        }

        public Criteria andOriginalContentLessThan(String value) {
            addCriterion("original_content <", value, "originalContent");
            return (Criteria) this;
        }

        public Criteria andOriginalContentLessThanOrEqualTo(String value) {
            addCriterion("original_content <=", value, "originalContent");
            return (Criteria) this;
        }

        public Criteria andOriginalContentLike(String value) {
            addCriterion("original_content like", value, "originalContent");
            return (Criteria) this;
        }

        public Criteria andOriginalContentNotLike(String value) {
            addCriterion("original_content not like", value, "originalContent");
            return (Criteria) this;
        }

        public Criteria andOriginalContentIn(List<String> values) {
            addCriterion("original_content in", values, "originalContent");
            return (Criteria) this;
        }

        public Criteria andOriginalContentNotIn(List<String> values) {
            addCriterion("original_content not in", values, "originalContent");
            return (Criteria) this;
        }

        public Criteria andOriginalContentBetween(String value1, String value2) {
            addCriterion("original_content between", value1, value2, "originalContent");
            return (Criteria) this;
        }

        public Criteria andOriginalContentNotBetween(String value1, String value2) {
            addCriterion("original_content not between", value1, value2, "originalContent");
            return (Criteria) this;
        }

        public Criteria andParticipledIsNull() {
            addCriterion("participled is null");
            return (Criteria) this;
        }

        public Criteria andParticipledIsNotNull() {
            addCriterion("participled is not null");
            return (Criteria) this;
        }

        public Criteria andParticipledEqualTo(Boolean value) {
            addCriterion("participled =", value, "participled");
            return (Criteria) this;
        }

        public Criteria andParticipledNotEqualTo(Boolean value) {
            addCriterion("participled <>", value, "participled");
            return (Criteria) this;
        }

        public Criteria andParticipledGreaterThan(Boolean value) {
            addCriterion("participled >", value, "participled");
            return (Criteria) this;
        }

        public Criteria andParticipledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("participled >=", value, "participled");
            return (Criteria) this;
        }

        public Criteria andParticipledLessThan(Boolean value) {
            addCriterion("participled <", value, "participled");
            return (Criteria) this;
        }

        public Criteria andParticipledLessThanOrEqualTo(Boolean value) {
            addCriterion("participled <=", value, "participled");
            return (Criteria) this;
        }

        public Criteria andParticipledIn(List<Boolean> values) {
            addCriterion("participled in", values, "participled");
            return (Criteria) this;
        }

        public Criteria andParticipledNotIn(List<Boolean> values) {
            addCriterion("participled not in", values, "participled");
            return (Criteria) this;
        }

        public Criteria andParticipledBetween(Boolean value1, Boolean value2) {
            addCriterion("participled between", value1, value2, "participled");
            return (Criteria) this;
        }

        public Criteria andParticipledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("participled not between", value1, value2, "participled");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table corpus
     *
     * @mbg.generated do_not_delete_during_merge Sun Mar 15 15:31:58 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table corpus
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}