package com.wcq.tang.model;

import java.util.Date;

public class Operation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.operation_id
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private Long operationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.operation_kind
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private Integer operationKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.operation_date
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private Date operationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.operation_content
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private String operationContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.operation_id
     *
     * @return the value of operation.operation_id
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Long getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.operation_id
     *
     * @param operationId the value for operation.operation_id
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setOperationId(Long operationId) {
        this.operationId = operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.operation_kind
     *
     * @return the value of operation.operation_kind
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Integer getOperationKind() {
        return operationKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.operation_kind
     *
     * @param operationKind the value for operation.operation_kind
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setOperationKind(Integer operationKind) {
        this.operationKind = operationKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.operation_date
     *
     * @return the value of operation.operation_date
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Date getOperationDate() {
        return operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.operation_date
     *
     * @param operationDate the value for operation.operation_date
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.operation_content
     *
     * @return the value of operation.operation_content
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public String getOperationContent() {
        return operationContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.operation_content
     *
     * @param operationContent the value for operation.operation_content
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setOperationContent(String operationContent) {
        this.operationContent = operationContent == null ? null : operationContent.trim();
    }
}