package com.wcq.tang.model;

import java.util.Date;

public class Original {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.original_id
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private Long originalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.uploader
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private Long uploader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.title
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.tags
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.original_date
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private Date originalDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.source
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.format
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private String format;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.formated
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private Boolean formated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.cleaned
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private Boolean cleaned;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.address
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.txt_path
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private String txtPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.clean_path
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    private String cleanPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.original_id
     *
     * @return the value of original.original_id
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Long getOriginalId() {
        return originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.original_id
     *
     * @param originalId the value for original.original_id
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setOriginalId(Long originalId) {
        this.originalId = originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.uploader
     *
     * @return the value of original.uploader
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Long getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.uploader
     *
     * @param uploader the value for original.uploader
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setUploader(Long uploader) {
        this.uploader = uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.title
     *
     * @return the value of original.title
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.title
     *
     * @param title the value for original.title
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.tags
     *
     * @return the value of original.tags
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.tags
     *
     * @param tags the value for original.tags
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.original_date
     *
     * @return the value of original.original_date
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Date getOriginalDate() {
        return originalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.original_date
     *
     * @param originalDate the value for original.original_date
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setOriginalDate(Date originalDate) {
        this.originalDate = originalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.source
     *
     * @return the value of original.source
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.source
     *
     * @param source the value for original.source
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.format
     *
     * @return the value of original.format
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.format
     *
     * @param format the value for original.format
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setFormat(String format) {
        this.format = format == null ? null : format.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.formated
     *
     * @return the value of original.formated
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Boolean getFormated() {
        return formated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.formated
     *
     * @param formated the value for original.formated
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setFormated(Boolean formated) {
        this.formated = formated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.cleaned
     *
     * @return the value of original.cleaned
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public Boolean getCleaned() {
        return cleaned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.cleaned
     *
     * @param cleaned the value for original.cleaned
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setCleaned(Boolean cleaned) {
        this.cleaned = cleaned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.address
     *
     * @return the value of original.address
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.address
     *
     * @param address the value for original.address
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.txt_path
     *
     * @return the value of original.txt_path
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public String getTxtPath() {
        return txtPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.txt_path
     *
     * @param txtPath the value for original.txt_path
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setTxtPath(String txtPath) {
        this.txtPath = txtPath == null ? null : txtPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.clean_path
     *
     * @return the value of original.clean_path
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public String getCleanPath() {
        return cleanPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.clean_path
     *
     * @param cleanPath the value for original.clean_path
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    public void setCleanPath(String cleanPath) {
        this.cleanPath = cleanPath == null ? null : cleanPath.trim();
    }
}