package com.wcq.tang.model;

import java.util.Date;

public class Threecup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threecup.three_id
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    private Long threeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threecup.subject
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threecup.predicate
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    private String predicate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threecup.object
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    private String object;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threecup.uploader
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    private Long uploader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column threecup.build_time
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    private Date buildTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threecup.three_id
     *
     * @return the value of threecup.three_id
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public Long getThreeId() {
        return threeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threecup.three_id
     *
     * @param threeId the value for threecup.three_id
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public void setThreeId(Long threeId) {
        this.threeId = threeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threecup.subject
     *
     * @return the value of threecup.subject
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threecup.subject
     *
     * @param subject the value for threecup.subject
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threecup.predicate
     *
     * @return the value of threecup.predicate
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public String getPredicate() {
        return predicate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threecup.predicate
     *
     * @param predicate the value for threecup.predicate
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public void setPredicate(String predicate) {
        this.predicate = predicate == null ? null : predicate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threecup.object
     *
     * @return the value of threecup.object
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public String getObject() {
        return object;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threecup.object
     *
     * @param object the value for threecup.object
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public void setObject(String object) {
        this.object = object == null ? null : object.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threecup.uploader
     *
     * @return the value of threecup.uploader
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public Long getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threecup.uploader
     *
     * @param uploader the value for threecup.uploader
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public void setUploader(Long uploader) {
        this.uploader = uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column threecup.build_time
     *
     * @return the value of threecup.build_time
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public Date getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column threecup.build_time
     *
     * @param buildTime the value for threecup.build_time
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }
}