package com.wcq.tang.model;

import java.util.Date;

public class Todaythree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todaythree.id
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todaythree.three_id
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    private Long threeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todaythree.subject
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todaythree.predicate
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    private String predicate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todaythree.object
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    private String object;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todaythree.op_time
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    private Date opTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todaythree.op_user
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    private Long opUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todaythree.id
     *
     * @return the value of todaythree.id
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todaythree.id
     *
     * @param id the value for todaythree.id
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todaythree.three_id
     *
     * @return the value of todaythree.three_id
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public Long getThreeId() {
        return threeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todaythree.three_id
     *
     * @param threeId the value for todaythree.three_id
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public void setThreeId(Long threeId) {
        this.threeId = threeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todaythree.subject
     *
     * @return the value of todaythree.subject
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todaythree.subject
     *
     * @param subject the value for todaythree.subject
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todaythree.predicate
     *
     * @return the value of todaythree.predicate
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public String getPredicate() {
        return predicate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todaythree.predicate
     *
     * @param predicate the value for todaythree.predicate
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public void setPredicate(String predicate) {
        this.predicate = predicate == null ? null : predicate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todaythree.object
     *
     * @return the value of todaythree.object
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public String getObject() {
        return object;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todaythree.object
     *
     * @param object the value for todaythree.object
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public void setObject(String object) {
        this.object = object == null ? null : object.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todaythree.op_time
     *
     * @return the value of todaythree.op_time
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todaythree.op_time
     *
     * @param opTime the value for todaythree.op_time
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todaythree.op_user
     *
     * @return the value of todaythree.op_user
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public Long getOpUser() {
        return opUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todaythree.op_user
     *
     * @param opUser the value for todaythree.op_user
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    public void setOpUser(Long opUser) {
        this.opUser = opUser;
    }
}