package com.wcq.tang.mapper;

import com.wcq.tang.model.Indexmsg;
import com.wcq.tang.model.IndexmsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndexmsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexmsg
     *
     * @mbg.generated Wed Mar 04 13:21:35 CST 2020
     */
    long countByExample(IndexmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexmsg
     *
     * @mbg.generated Wed Mar 04 13:21:35 CST 2020
     */
    int deleteByExample(IndexmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexmsg
     *
     * @mbg.generated Wed Mar 04 13:21:35 CST 2020
     */
    int deleteByPrimaryKey(Integer msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexmsg
     *
     * @mbg.generated Wed Mar 04 13:21:35 CST 2020
     */
    int insert(Indexmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexmsg
     *
     * @mbg.generated Wed Mar 04 13:21:35 CST 2020
     */
    int insertSelective(Indexmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexmsg
     *
     * @mbg.generated Wed Mar 04 13:21:35 CST 2020
     */
    List<Indexmsg> selectByExample(IndexmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexmsg
     *
     * @mbg.generated Wed Mar 04 13:21:35 CST 2020
     */
    Indexmsg selectByPrimaryKey(Integer msgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexmsg
     *
     * @mbg.generated Wed Mar 04 13:21:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") Indexmsg record, @Param("example") IndexmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexmsg
     *
     * @mbg.generated Wed Mar 04 13:21:35 CST 2020
     */
    int updateByExample(@Param("record") Indexmsg record, @Param("example") IndexmsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexmsg
     *
     * @mbg.generated Wed Mar 04 13:21:35 CST 2020
     */
    int updateByPrimaryKeySelective(Indexmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indexmsg
     *
     * @mbg.generated Wed Mar 04 13:21:35 CST 2020
     */
    int updateByPrimaryKey(Indexmsg record);
}