package com.wcq.tang.mapper;

import com.wcq.tang.model.Operation;
import com.wcq.tang.model.OperationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    long countByExample(OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    int deleteByExample(OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    int deleteByPrimaryKey(Long operationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    int insert(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    int insertSelective(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    List<Operation> selectByExample(OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    Operation selectByPrimaryKey(Long operationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") Operation record, @Param("example") OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    int updateByExample(@Param("record") Operation record, @Param("example") OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    int updateByPrimaryKeySelective(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Sun Mar 15 15:31:58 CST 2020
     */
    int updateByPrimaryKey(Operation record);
}