package com.wcq.tang.mapper;

import com.wcq.tang.model.Threecup;
import com.wcq.tang.model.ThreecupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.cache.annotation.Caching;

public interface ThreecupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threecup
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    long countByExample(ThreecupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threecup
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    @CacheEvict(cacheNames = {"thra","thru"},allEntries = true)
    int deleteByExample(ThreecupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threecup
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    @Caching(evict = {
            @CacheEvict(cacheNames = {"thra","thru"},allEntries = true),
            @CacheEvict(cacheNames = "thr",key = "#threeId")
    })
    int deleteByPrimaryKey(Long threeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threecup
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    @CacheEvict(cacheNames = {"thra","thru"},allEntries = true)
    int insert(Threecup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threecup
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    @CacheEvict(cacheNames = {"thra","thru"},allEntries = true)
    int insertSelective(Threecup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threecup
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    List<Threecup> selectByExample(ThreecupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threecup
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    @Cacheable(cacheNames = "thr")
    Threecup selectByPrimaryKey(Long threeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threecup
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    @Caching(evict = {
            @CacheEvict(cacheNames = {"thra","thru"},allEntries = true),
            @CacheEvict(cacheNames = "thr",allEntries = true)
    })
    int updateByExampleSelective(@Param("record") Threecup record, @Param("example") ThreecupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threecup
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    @Caching(evict = {
            @CacheEvict(cacheNames = {"thra","thru"},allEntries = true),
            @CacheEvict(cacheNames = "thr",allEntries = true)
    })
    int updateByExample(@Param("record") Threecup record, @Param("example") ThreecupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threecup
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    @Caching(evict = {
            @CacheEvict(cacheNames = {"thra","thru"},allEntries = true),
            @CacheEvict(cacheNames = "thr",key = "#record.threeId")
    })
    int updateByPrimaryKeySelective(Threecup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threecup
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    @Caching(evict = {
            @CacheEvict(cacheNames = {"thra","thru"},allEntries = true),
            @CacheEvict(cacheNames = "thr",key = "#record.threeId")
    })
    int updateByPrimaryKey(Threecup record);
}