package com.wcq.tang.mapper;

import com.wcq.tang.model.Todaythree;
import com.wcq.tang.model.TodaythreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TodaythreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todaythree
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    long countByExample(TodaythreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todaythree
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    int deleteByExample(TodaythreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todaythree
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todaythree
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    int insert(Todaythree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todaythree
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    int insertSelective(Todaythree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todaythree
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    List<Todaythree> selectByExample(TodaythreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todaythree
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    Todaythree selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todaythree
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") Todaythree record, @Param("example") TodaythreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todaythree
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    int updateByExample(@Param("record") Todaythree record, @Param("example") TodaythreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todaythree
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    int updateByPrimaryKeySelective(Todaythree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todaythree
     *
     * @mbg.generated Mon Mar 16 13:58:12 CST 2020
     */
    int updateByPrimaryKey(Todaythree record);
}