package com.wcq.tang.mapper;

import com.wcq.tang.model.Todayop;
import com.wcq.tang.model.TodayopExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TodayopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todayop
     *
     * @mbg.generated Mon Mar 16 13:07:48 CST 2020
     */
    long countByExample(TodayopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todayop
     *
     * @mbg.generated Mon Mar 16 13:07:48 CST 2020
     */
    int deleteByExample(TodayopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todayop
     *
     * @mbg.generated Mon Mar 16 13:07:48 CST 2020
     */
    int deleteByPrimaryKey(Integer opId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todayop
     *
     * @mbg.generated Mon Mar 16 13:07:48 CST 2020
     */
    int insert(Todayop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todayop
     *
     * @mbg.generated Mon Mar 16 13:07:48 CST 2020
     */
    int insertSelective(Todayop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todayop
     *
     * @mbg.generated Mon Mar 16 13:07:48 CST 2020
     */
    List<Todayop> selectByExample(TodayopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todayop
     *
     * @mbg.generated Mon Mar 16 13:07:48 CST 2020
     */
    Todayop selectByPrimaryKey(Integer opId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todayop
     *
     * @mbg.generated Mon Mar 16 13:07:48 CST 2020
     */
    int updateByExampleSelective(@Param("record") Todayop record, @Param("example") TodayopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todayop
     *
     * @mbg.generated Mon Mar 16 13:07:48 CST 2020
     */
    int updateByExample(@Param("record") Todayop record, @Param("example") TodayopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todayop
     *
     * @mbg.generated Mon Mar 16 13:07:48 CST 2020
     */
    int updateByPrimaryKeySelective(Todayop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todayop
     *
     * @mbg.generated Mon Mar 16 13:07:48 CST 2020
     */
    int updateByPrimaryKey(Todayop record);
}